export const dogBreeds = [
  "Mixed Breed",
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alapaha Blue Blood Bulldog",
  "Alaskan Malamute",
  "American Bulldog",
  "American Bully",
  "American Cocker Spaniel",
  "Anatolian Shepherd",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Shepherd",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Basenji",
  "Basset Bleu De Gascogne",
  "Basset Fauve De Bretagne",
  "Basset Griffon Vendeen",
  "Basset Hound",
  "Bavarian Mountain Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Shepherd Dog",
  "Bergamasco",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Biewer Terrier",
  "Bloodhound",
  "Boerboel",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier Des Flandres",
  "Boxer",
  "Bracco Italiano",
  "Braque d Auvergne",
  "Briard",
  "Brittany Spaniel",
  "Bullmastiff",
  "Cairn Terrier",
  "Canaan Dog",
  "Canadian Eskimo Dog",
  "Cane Corso",
  "Catalan Sheepdog",
  "Caucasian Shepherd Dog",
  "Cavachon",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Central Asian Shepherd",
  "Cesky Terrier",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chorkie",
  "Chow Chow",
  "Chug",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Coonhound",
  "Coton De Tulear",
  "Curly Coated Retriever",
  "Dachshund",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Deerhound",
  "Dobermann",
  "Dogue De Bordeaux",
  "Dorset Olde Tyme Bulldogge",
  "English Bull Terrier",
  "English Bulldog",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Terrier",
  "Entlebucher Mountain Dog",
  "Estrela Mountain Dog",
  "Eurasier",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat coated Retriever",
  "Fox Terrier",
  "Foxhound",
  "French Bulldog",
  "German Longhaired Pointer",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Spitz",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Goldador",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Grand Bleu De Gascogne",
  "Great Dane",
  "Greater Swiss Mountain Dog",
  "Greenland Dog",
  "Greyhound",
  "Griffon Bruxellois",
  "Hamiltonstovare",
  "Harrier",
  "Havanese",
  "Hovawart",
  "Hungarian Puli",
  "Hungarian Pumi",
  "Hungarian Vizsla",
  "Huntaway",
  "Ibizan Hound",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Italian Spinone",
  "Jack Russell",
  "Jackapoo",
  "Jagdterrier",
  "Japanese Akita Inu",
  "Japanese Chin",
  "Japanese Shiba Inu",
  "Japanese Spitz",
  "Jug",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Kooikerhondje",
  "Korthals Griffon",
  "Kromfohrlander",
  "Labradoodle",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Large Munsterlander",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen",
  "Lurcher",
  "Malshi",
  "Maltese",
  "Maltipoo",
  "Manchester Terrier",
  "Maremma Sheepdog",
  "Mastiff",
  "Mexican Hairless",
  "Miniature Dachshund",
  "Miniature Pinscher",
  "Miniature Poodle",
  "Miniature Schnauzer",
  "Morkie",
  "Neapolitan Mastiff",
  "Newfoundland",
  "Norfolk Terrier",
  "Northern Inuit",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Old Tyme Bulldog",
  "Otterhound",
  "Papillon",
  "Parson Russell",
  "Patterdale Terrier",
  "Pekingese",
  "Pharaoh Hound",
  "Picardy Spaniel",
  "Pinscher",
  "Plummer Terrier",
  "Pointer",
  "Polish Lowland Sheepdog ",
  "Pomchi",
  "Pomeranian",
  "Pomsky",
  "Poochon",
  "Poodle",
  "Portuguese Podengo",
  "Portuguese Sheepdog",
  "Portuguese Water Dog",
  "Presa Canario",
  "Pug",
  "Puggle",
  "Pyrenean Mastiff",
  "Pyrenean Mountain Dog",
  "Pyrenean Sheepdog",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Russian Black Terrier",
  "Russian Toy Terrier",
  "Saarloos Wolfdog",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Schnoodle",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Shihpoo",
  "Shorkie",
  "Siberian Husky",
  "Skye Terrier",
  "Sloughi",
  "Smooth Collie",
  "Soft Coated Wheaten Terrier",
  "Spanish Water Dog",
  "Sporting Lucas Terrier",
  "Springador",
  "Sprocker",
  "Sprollie",
  "Sproodle",
  "Staffordshire Bull Terrier",
  "Standard Poodle",
  "Sussex Spaniel",
  "Swedish Lapphund",
  "Swedish Vallhund",
  "Thai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Poodle",
  "Turkish Kangal",
  "Utonagan",
  "Weimaraner",
  "Welsh Collie",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland Terrier",
  "Whippet",
  "White Swiss Shepherd",
  "Yorkshire Terrier"
];
